# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5079efe9ad15aef6f5373fd0e94c79dd747f75b96534104be41a6500d379b077cf319d269cbd8f302d319fef260283cc32224990a1e6a4942a831b809af4820a

test:
  secret_key_base: 9d5dc51e9e4e7bac38132594614cf48168f9b38b222f849037f338f1ae1cb95437d13d5848b703b4f153fcb08cb93c7b60f762a96262dbc15c0680b21d59cccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
